### ISSUE TITLE
Bf1 Problemy

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/BattlefieldOne#1]
Korzystam z 2 moda bf1 lecz jest problem

- asysty nie działają 

- cras Hud po 100H na serwerze 
(Problem leży po stronie stopni po osiągnięciu ostatniej znika hud co zauważyłem przy 10000H hud zaczyna mrugać i mamy 300ping 
Problem odnaleziony w public display_hud(id) lecz nie potrafię go naprawić )

- odznaka niewidzialność nie działa
(Raz na jakiś czas zadziała na 4 poziomie prawie nie działa
Co zauważyłem to tak jak by jej wcale nie przyznawało)

- sklep sms odznaki nie działa (Korzystam z płatnego sklepu)

byłbym wdzięczny jak byś to naprawił bo przyjemnie się gra na tym modzie

**Comment by TheDoctor0** [comment]
Witaj.
Co do tych problemów:
1. Silnik nie posiada własnej obsługi asyst, a jedynie umożliwia ich integrację.
Należy skorzystać z jakiegokolwiek zewnętrznego pluginu asyst (np. [Kill Asysta](https://github.com/TheDoctor0/AMXXLegacy/blob/master/kill_asysta.sma)) i użyć natywu _bf1_add_assist_kill(id)_.
2. To wygląda na faktyczny problem.
3. Do zweryfikowania.
4. Jeśli korzystasz z sklepu innego niż [sklep-sms.pl](https://sklep-sms.pl/) to ten gotowy plugin z oczywistych względów nie zadziała. Musisz napisać sobie własny zgodnie z tym jak używany przez ciebie sklep działa.

**Comment by TheDoctor0** [comment]
[v2.0.](https://github.com/TheDoctor0/BattlefieldOne/releases/latest)
