### ISSUE TITLE
Bf1 Poprawka

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/BattlefieldOne#2]
Witam wiem ze cie męczę ale wracam z kilkoma sprawami tym razem 2 ps nie złość się :D 

- Hud crash po zdobyciu max zabić czyli 1500 to samo co przy czasie hud znika lub buguje się
- Asysty dobijają zabić po 2 do hud  czyli gracz za 10 zabić zwykłych w hud ma 20

**Comment by TheDoctor0** [comment]
Nie masz za co przepraszać, jeśli są błędy, to trzeba je poprawić.
1. Problemu z wyświetlaniem samego HUD tutaj nie miałem, natomiast zauważyłem błąd w pętli sprawdzającej rangi - i zostało to [poprawione](https://github.com/TheDoctor0/BattlefieldOne/releases/tag/2.1).
2. Nie udało mi się w żaden sposób tego zreplikować, a testowałem to mając CS'a odpalonego trzy razy, aby nabijać asysty.
