### ISSUE TITLE
Mały Problem

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/BattlefieldOne#3]
Nie wiem czy zauważyłeś ale poprawiłeś wersje która ma błąd z wydania z wcześniejszej wersji z czasem aktualnie zabicia działają ale po 100h znika hud

**Comment by TheDoctor0** [comment]
Powiedziałbym, że jednak wszystko zdaje się działać jak powinno:
![20200421130018_1](https://user-images.githubusercontent.com/16612504/79858691-18c19f00-83d0-11ea-97ba-31159ab51cea.jpg)

Poprawka była zrobiona [tutaj](https://github.com/TheDoctor0/BattlefieldOne/commit/325bd08f020494536648bb4e452568afabc0e85e).

**Comment by xHadesSoulx** [comment]
A zostało poprawne wrzucone do pobrania bo jestem pewien że wina leży po stronie czasu gdy zdobędę ostatni stopień to hud znika ale już nie całkiem tylko częściowo  

statusText zostaje ale już Hud i DHud znika 
częściowo to załatałem na spartana dodając kolejny stopień z czasem nie do osiągnięcia ale to nie załatwia problemu.
Chyba że jest tu winne zdobycie ostatniego stopnia ale jeśli tobie działa a mi na wersji 2.1 nie to ja już nie wiem. 

 Jeśli trzeba nagram filmik

**Comment by TheDoctor0** [comment]
Właśnie sprawdziłem pobierając pliki .amxx z release wersji 2.1 czy nie wrzuciłem czasem starszej wersji bez tej poprawki - nic takiego jednak nie miało miejsca.
Usunąłem sobie nawet celowo rangę za czas w bazie, żeby plugin mógł jeszcze raz sobie ją wyliczyć - i tutaj nie ma z tym żadnego problemu.

Jeśli kompilujesz sobie plugin lokalnie porównaj kod z [aktualnym](https://github.com/TheDoctor0/BattlefieldOne/blob/master/bf1_mod.sma#L1979).
Sama poprawka była zresztą bardzo prosta i po osiągnięciu ostatniej rangi czas przestaje być sprawdzany.

Możesz też sprawdzić sobie w bazie czy w kolumnie _degree_ nie posiadasz czasem wartości większej niż 4, bo to jest właśnie ostatnia ranga za czas.

**Comment by xHadesSoulx** [comment]
Zmieniałeś coś przy połączeniu z bazą danych bo odkryłem już w czym leży problem  jeśli osobie się już zawiesił hud to będzie już cały czas taki chyba że zmienię tą wartość tak jak psiałem wcześniej ale nowa osoba jak wejdzie na serwer już tego problemu nie mają

**Comment by TheDoctor0** [comment]
> Możesz też sprawdzić sobie w bazie czy w kolumnie degree nie posiadasz czasem wartości większej niż 4, bo to jest właśnie ostatnia ranga za czas.

Najłatwiej jest właściwie wywołać masowe zapytanie do bazy, żeby zmienić ewentualną błędną rangę:
```UPDATE `bf1` SET `degree` = 4 WHERE `degree` > 4;```

**Comment by xHadesSoulx** [comment]
ok pomogło dzięki wielkie
