### ISSUE TITLE
Problem z niewidzialnością

### ISSUE THREAD

**Issue by AlkoholikDrajwerxD** [TheDoctor0/BattlefieldOne#4]
Hej. Nie działa niewidzialność na nożu w odznace czasowej , niektórym nie pokazuje w trakcie życia hud'a. Poza tym nie zauważyłem innych błędów na ten moment. Poradzisz jak sobie z tym poradzić ? :)

**Comment by TheDoctor0** [comment]
Witaj.
Powiem szczerze, że po tym opisie bardziej wygląda to na problem z modułem hamsandwich niż samym modem.

Wklej output z następujących komend:
- meta version
- meta list
- amxx version
- amxx plugins

**Comment by AlkoholikDrajwerxD** [comment]
meta version
Metamod v1.21p37  2013/05/30 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v37
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: May 30 2013, 11:41:16 EET (optimized)

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] dproto_EF        RUN   -    dproto_i386.so    v0.9.391  ini   Start Never
 [ 2] VoiceTranscoder  RUN   -    vtc.so            v80       ini   ANY   ANY  
 [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini   Start ANY  
 [ 4] POD-Bot mm       RUN   -    podbot_mm_i386.s  vV3B21    ini   Chlvl ANY  
 [ 5] Bot Player Time  RUN   -    bot_played_time_  v1.2.0-d  ini   ANY   ANY  
 [ 6] MySQL            RUN   -    mysql_amxx_i386.  v1.8.2    pl3   ANY   ANY  
 [ 7] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl3   ANY   ANY  
 [ 8] Engine           RUN   -    engine_amxx_i386  v1.8.2    pl3   ANY   ANY  
 [ 9] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.2    pl3   ANY   ANY  
 [10] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2    pl3   ANY   ANY  
 [11] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl3   ANY   ANY  
 [12] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl3   ANY   ANY  

amxx version
AMX Mod X 1.8.2 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Feb 14 2013, 00:55:09
Build ID: 1.8.2 61:2ae84f7c0a97
Core mode: JIT+ASM32

amxx plugins
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.8.2       AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running  
 [  9] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running  
 [ 10] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running  
 [ 11] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running  
 [ 12] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running  
 [ 13] Scrolling Message       1.8.2       AMXX Dev Team     scrollmsg.amxx   running  
 [ 14] Info. Messages          1.8.2       AMXX Dev Team     imessage.amxx    running  
 [ 15] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running  
 [ 16] StatsX                  1.8.2       AMXX Dev Team     statsx.amxx      running  
 [ 17] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running  
 [ 18] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running  
 [ 19] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running  
 [ 20] Team Balancer           1.8b3       Ptahhotep         ptb.amxx         running  
 [ 21] Advanced Bullet Damage  1.0         Sn!ff3r           abd.amxx         running  
 [ 22] [CS] Team Semiclip      3.3.1       schmurgel1983     cs_team_semicli  running  
 [ 23] Voices Management       1.0.2       ConnorMcLeod      Voices_Manageme  running  
 [ 24] Parachute               1.3         KRoT@L/JTP10181   parachute.amxx   running  
 [ 25] Real Nade Drops         0.4         VEN               realnadedrops.a  running  
 [ 26] AntiFlash FINAL         5.0         Leo_[BH]          antiflash5.amxx  running  
 [ 27] Bomb Explode 3 Sounds   0.3         Simivar           bomb_explode_3s  running  
 [ 28] Galileo                 1.1.290     Brad Jones        galileo.amxx     running  
 [ 29] Polski KillStreak       1.6         Dizzy & Sn!ff3r   ultimate_sounds  running  
 [ 30] Restrict Weapons        1.8.2       AMXX Dev Team     restmenu.amxx    running  
 [ 31] unknown                 unknown     unknown           killassist.amxx  bad load 
 [ 32] Poprawne rate           1.0         Sn!ff3r           poprawne_rate.a  running  
 [ 33] BS Limiter              1.1.1       Pavulon           bs_limiter.amxx  running  
 [ 34] Alternative End Round   2.3b        Arkshine          alt_end_round_s  paused   
 [ 35] Reset Score             1.0         Silenttt          resetscore.amxx  running  
 [ 36] Automatyczna mala mapa  1.0         AlkoholikDrajwer  amx_mala_mapa.a  running  
 [ 37] Ultimate Gore           1.6         JTP10181          amx_gore_ultima  running  
 [ 38] Battlefield One Mod     1.2         O'zone  battlefield_one  running  
 [ 39] [SCM] Entity Editor     1.3.1       schmurgel1983     scm_entity_edit  running

**Comment by TheDoctor0** [comment]
> AMX Mod X 1.8.2 (http://www.amxmodx.org)

Korzystasz z niewspieranej tutaj wersji AMXX.
Zaktualizuj serwer do AMXX 1.8.3+ korzystając np. z gotowego [BasePack](https://github.com/AMXX-pl/BasePack).

> [ 38] Battlefield One Mod 1.2 O'zone battlefield_one running

Zaktualizuj też samego moda, aktualna wersja to [2.1](https://github.com/TheDoctor0/BattlefieldOne/releases/tag/2.1).

**Comment by AlkoholikDrajwerxD** [comment]
Zaktualizowałem serwer , zaktualizowałem moda - wszystko działa , dziękuje za pomoc
