### ISSUE TITLE
Pytanie na temat pluginu vipa

### ISSUE THREAD

**Issue by AlkoholikDrajwerxD** [TheDoctor0/BattlefieldOne#5]
Cześć , czy jest możliwość współpracy twojego pluginu vipa z pluginem który daje wszystkim VIPa w określonych godzinach ? Plugin nocny nadaje flagi użytkownikom będącym na serwerze natomiast niekoniecznie to działa ze strony BF1 VIP. 
Domyślam sie że wynika to z tego że plugin VIP sprawdza użytkownikom flagi tylko podczas wejścia na serwer / załadowania mapy a nie co jakiś czas gdy jesteśmy już na serwerze.

**Comment by TheDoctor0** [comment]
Witaj.
Tak, ze względu na to jak VIP jest obsługiwany wykorzystanie tego pluginu byłoby dość utrudnione.
Natomiast bez żadnego problemu można dopisać taką funkcjonalność do samego VIPa.
